# This file is used to configure the environment commands.

# This section is used to configure the speed up effect for time fast-forward smoothly over five seconds
speedUpEffect:
  enabled: true

# This section is used to configure the time commands.
times:
  day:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Time set to <green>Day</green></white>'
        - '[sound] ui.button.click'

  night:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Time set to <green>Night</green></white>'
        - '[sound] ui.button.click'

weather:
  rain:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Weather set to <green>Rain</green></white>'
        - '[sound] ui.button.click'

  thunder:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Weather set to <green>Thunder</green></white>'
        - '[sound] ui.button.click'

  sun:
    commands_when_ran:
      enabled: true
      actions:
        - '[actionbar] <white>Weather set to <green>Sun</green></white>'
        - '[sound] ui.button.click'
